export * from "./NoticeModal";
export * from "./ResultCard";
export * from "./ResultGroup";
export * from "./HeroSection";
export * from "./ResultSection";
export * from "./AboutSection";
export * from "./FeaturesSection";
export * from "./PrivacySection";
export * from "./PlatformsSection";
